# Generated by Django 3.2.3 on 2021-05-29 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=30)),
                ('staff_type', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=40, null=True)),
                ('employee_address', models.CharField(max_length=256, null=True)),
                ('employee_phone', models.CharField(max_length=256, null=True)),
                ('employee_email', models.CharField(max_length=256)),
                ('employee_zipcode', models.CharField(max_length=256)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staffteam')),
            ],
        ),
    ]
