# Generated by Django 3.2.7 on 2021-12-11 06:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_samplemanger'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='samplemanger',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
