# Generated by Django 3.2.7 on 2021-12-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_samplemanger_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='samplemanger',
            managers=[
            ],
        ),
    ]
